---
# Run stashbot on kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stashbot.libera
  namespace: tool-stashbot
  labels:
    name: stashbot.libera
    toolforge: tool
spec:
  replicas: 1
  selector:
    matchLabels:
      name: stashbot.libera
      toolforge: tool
  template:
    metadata:
      labels:
        name: stashbot.libera
        toolforge: tool
    spec:
      containers:
        - name: bot
          image: docker-registry.tools.wmflabs.org/toolforge-python37-sssd-base:latest
          command:
            - "/data/project/stashbot/bin/stashbot.sh"
            - "run"
          workingDir: /data/project/stashbot
          env:
            - name: HOME
              value: /data/project/stashbot
          imagePullPolicy: Always
