---
# Run stashbot on kubernetes
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: stashbot.bot
  namespace: stashbot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: stashbot.bot
    spec:
      containers:
        - name: bot
          image: docker-registry.tools.wmflabs.org/toollabs-python35-base:latest
          command: [ "/data/project/stashbot/bin/stashbot.sh", "run" ]
          workingDir: /data/project/stashbot
          env:
            - name: HOME
              value: /data/project/stashbot
          imagePullPolicy: Always
          volumeMounts:
            - name: home
              mountPath: /data/project/stashbot/
      volumes:
        - name: home
          hostPath:
            path: /data/project/stashbot/
